name: 'Compare Code Coverage'
description: 'Compares code coverage between the current branch and a target branch using PCOV or Xdebug.'
author: 'Your Name'
inputs:
  coverage-tool:
    description: 'The code coverage tool to use (pcov or xdebug).'
    required: false
    default: 'pcov'
  target-branch:
    description: 'The branch to compare against (default is HEAD).'
    required: false
    default: 'HEAD'
runs:
  using: 'composite'
  steps:
    - name: Run the code coverage comparison
      shell: bash
      run: ./entrypoint.sh ${{ inputs.coverage-tool }} ${{ inputs.target-branch }}
